name: agriculture_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.8

  # Localization
  easy_localization: ^3.0.8

  # Screen utils
  flutter_screenutil: ^5.9.3

  # Device preview for debugging
  device_preview: ^1.2.0

  # Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4

  # State management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  get_it: ^9.1.0

  # Networking
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  http: ^1.6.0
  signalr_core: ^1.1.2

  # Notifications
  flutter_local_notifications: ^19.5.0

  # Images
  image_picker: ^1.2.1
  badges: ^3.1.2

  # Supabase
  supabase_flutter: ^2.12.0

  # Environment variables
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Flutter launcher icons
  flutter_launcher_icons: ^0.14.4
flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#0A3D38"
  adaptive_icon_foreground: "assets/images/logo.png"


